<?php

namespace Erp\VendorBundle\Entity;

/**
 * VendorCreateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VendorCreateRepository extends \Doctrine\ORM\EntityRepository
{
}
