<?php

namespace Erp\VendorBundle\Entity;

/**
 * VendorEditRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VendorEditRepository extends \Doctrine\ORM\EntityRepository
{
    public function getVendorById($id) {
        $qb = $this->_em->createQueryBuilder()
            ->select('a')
            ->from($this->_entityName, 'a')
            ->where('a.id = :vendorId')
            ->setParameter('vendorId', $id);

        $result = $qb->getQuery()->getOneOrNullResult();

        return $result;
    }


}
