erp_stripe_webhook:
    resource: "@ErpStripeBundle/Resources/config/routing/webhook.yml"
    prefix: /

erp_stripe_transaction:
    resource: "@ErpStripeBundle/Resources/config/routing/transaction.yml"
    prefix: /dashboard

erp_stripe_invoice:
    resource: "@ErpStripeBundle/Resources/config/routing/invoice.yml"
    prefix: /dashboard

erp_stripe_cashflow:
    resource: "@ErpStripeBundle/Resources/config/routing/cashflow.yml"
    prefix: /dashboard