imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: '@SonataTranslationBundle/Resources/config/config.yml' }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    globals:
        fees: "@erp.core.fee.service"
        google_analytics_id: '%google.analytics.id%'
        stripe_public_key: '%stripe.public.key%'
        plaid_public_key: '%plaid.public.key%'
        plaid_env: '%plaid.env%'
        app_version: 'v%application_version%'
    form:
        resources:
            - 'SonataCoreBundle:Form:datepicker.html.twig'

# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ ]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        #closure:
        #    jar: "%kernel.root_dir%/Resources/java/compiler.jar"
        #yui_css:
        #    jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        server_version: 5.7
        mapping_types:
            enum: string

        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        dql:
            datetime_functions:
                date_format: DoctrineExtensions\Query\Mysql\DateFormat
                date: DoctrineExtensions\Query\Mysql\Date
                year: DoctrineExtensions\Query\Mysql\Year
                day: DoctrineExtensions\Query\Mysql\Day
            string_functions:
                month: DoctrineExtensions\Query\Mysql\Month

    dbal:
        types:
            json: Sonata\Doctrine\Types\JsonType

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    port:  "%mailer_port%"
    encryption:  "%mailer_encryption%"
    auth_mode:
#    spool:
#        type: file
#        path: "%kernel.cache_dir%/swiftmailer/spool"
    logging: "%kernel.debug%"

fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    use_listener: true
    use_username_form_type: true
    user_class: Erp\UserBundle\Entity\User
    service:
        mailer: fos_user.mailer.twig_swift
    resetting:
        token_ttl: 86400
        email:
            template: ErpUserBundle:Resetting:email.html.twig
        form:
            type: erp_users_form_reset_password
    from_email:
        address:  '%contact.email%'
        sender_name: "Zoobdoo"
    registration:
        form:
            type: erp_users_manager_form_registration

liip_imagine:
    driver: imagick
    cache: default
    data_loader: default
    resolvers:
        default:
            web_path:
                web_root: %kernel.root_dir%/../web/
                cache_prefix: cache
    loaders:
        default:
            filesystem:
                data_root: %kernel.root_dir%/../web/
    filter_sets:
        profile_image:
            quality: 85
            filters:
                thumbnail: { size: [90, 90], mode: outbound }
        property_card_image:
            quality: 85
            filters:
                thumbnail: { size: [260, 245], mode: outbound }
        property_details_carousel_inner:
            quality: 85
            filters:
                thumbnail: { size: [600, 440], mode: outbound }
        property_details_carousel_indicators:
            quality: 85
            filters:
                thumbnail: { size: [115, 140], mode: outbound }
        listings_325_300:
            quality: 85
            filters:
                thumbnail: { size: [325, 300], mode: outbound }
        listings_65_75:
            quality: 85
            filters:
                thumbnail: { size: [65, 75], mode: outbound }

sonata_doctrine_orm_admin:
    templates:
        form:
            - ErpAdminBundle:Form:form_admin_fields.html.twig

doctrine_migrations:
    dir_name: %kernel.root_dir%/DoctrineMigrations
    namespace: Application\Migrations
    table_name: migration_versions
    name: Application Migrations

sonata_admin:
    title:      Zoobdoo
    title_logo: bundles/erpadmin/images/admin_logo.png
    security:
        handler: sonata.admin.security.handler.role
    templates:
        dashboard: ErpAdminBundle::dashboard.html.twig
        user_block: ErpAdminBundle:Admin:user_block.html.twig

sonata_block:
    default_contexts: [sonata_page_bundle]
    blocks:
        # Enable the SonataAdminBundle block
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.admin.block.search_result:
            contexts: [admin]

sonata_translation:
    locales: [en]
    default_locale: en

knp_paginator:
    page_range: 10                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: ErpPropertyBundle:Listings:pagination.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

knp_menu:
    twig:  # use "twig: false" to disable the Twig extension and the TwigRenderer
        template: knp_menu.html.twig
    templating: true # if true, enables the helper for PHP templates
    default_renderer: twig # The renderer to use, list is also available by default

white_october_breadcrumbs:
    viewTemplate: '::breadcrumbs.html.twig'

ivory_ck_editor:
    input_sync: true
    default_config: oneview
    configs:
        oneview:
            toolbar: [['placeholder'],["Styles","Format","Font","FontSize","TextColor","BGColor","Undo","Redo","Bold","Italic","Underline","RemoveFormat"],["JustifyLeft","JustifyCenter","JustifyRight","JustifyBlock","Maximize","ShowBlocks"]]
            language: '%locale%'
            extraPlugins: "placeholder"
    plugins:
        placeholder:
            path:     '/bundles/erpcore/js/ckeditor/plugins/placeholder/'
            filename: 'main.js'

knp_snappy:
    temporary_folder: %kernel.cache_dir%/snappy
    pdf:
        enabled:    true
        binary:     'xvfb-run -- wkhtmltopdf'

old_sound_rabbit_mq:
    connections:
        default:
            host:     '%rabbitmq.host%'
            port:     '%rabbitmq.port%'
            user:     '%rabbitmq.user%'
            password: '%rabbitmq.password%'
            vhost:    '%rabbitmq.vhost%'
            lazy:     false
            connection_timeout: 3
            read_write_timeout: 3

            # requires php-amqplib v2.4.1+ and PHP5.4+
            keepalive: false

            # requires php-amqplib v2.4.1+
            heartbeat: 0

            #requires php_sockets.dll
            use_socket: false # default false
    producers:
        update_subscriptions:
            connection:       default
            exchange_options: {name: 'update-subscriptions', type: direct}
            service_alias:    update_subscriptions_producer
        send_notification:
            connection:       default
            exchange_options: {name: 'send-notification', type: direct}
            service_alias:    send_notification_service_producer
    consumers:
        update_subscriptions:
            connection:       default
            exchange_options: {name: 'update-subscriptions', type: direct}
            queue_options:    {name: 'update-subscriptions'}
            callback:         erp.payment.consumer.update_subscriptions
            enable_logger: true
        send_notification:
            connection:       default
            exchange_options: {name: 'send-notification', type: direct}
            queue_options:    {name: 'send-notification'}
            callback:         erp_notification.consumer.send_notification
            enable_logger: true

bukashk0zzz_hello_sign:
    login: '%hellosign_api_key%'