<?php

namespace Erp\PaymentBundle\Repository;

use \Doctrine\ORM\EntityRepository;
use Erp\UserBundle\Entity\User;

/**
 * PaySimpleHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaySimpleHistoryRepository extends EntityRepository
{
    /**
     * Get Manager payment history
     *
     * @param User           $user
     * @param null|\DateTime $startDate
     * @param null|\DateTime $endDate
     *
     * @return array
     */
    public function getManagerHistory(User $user, $startDate = null, $endDate = null)
    {
        $properties = $user->getProperties()->toArray();
        $qb = $this->_em->createQueryBuilder()
            ->select('psh')
            ->from($this->_entityName, 'psh')
            ->where('psh.property IN (:properties)')
            ->setParameter('properties', $properties)
            ->orderBy('psh.paymentDate', 'DESC');

        if ($startDate || $endDate) {
            if ($startDate) {
                $qb->andWhere('psh.paymentDate >=:startDate')
                    ->setParameter('startDate', $startDate);
            }

            if ($endDate) {
                $qb->andWhere('psh.paymentDate <=:endDate')
                    ->setParameter('endDate', $endDate);
            }
        } else {
            $qb->setMaxResults(100);
        }

        $result = $qb->getQuery()->getResult();

        return $result;
    }
}
