<?php

namespace Erp\PaymentBundle\Repository;

use \Doctrine\ORM\EntityRepository;

/**
 * PaySimpleDeferredPaymentsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaySimpleDeferredPaymentsRepository extends EntityRepository
{
}
