erp_property_application_form:
    path:     /{propertyId}/constructor
    defaults: { _controller: ErpPropertyBundle:ApplicationForm:constructor }
    methods: [GET, POST]
    requirements:
        propertyId: \d+

erp_property_application_form_charge:
    path:     /{propertyId}/constructor-charge
    defaults: { _controller: ErpPropertyBundle:ApplicationForm:constructorCharge }
    methods: [GET, POST]
    requirements:
        propertyId: \d+

erp_property_application_complete_form:
    path:     /{propertyId}/complete
    defaults: { _controller: ErpPropertyBundle:ApplicationForm:complete }
    methods: [GET, POST]
    requirements:
        propertyId: \d+

erp_property_application_remove_section:
    path:     /{propertyId}/remove-section/{sectionId}
    defaults: { _controller: ErpPropertyBundle:ApplicationForm:removeSection }
    methods: [GET, DELETE]
    requirements:
        propertyId: \d+
        sectionId: \d+

erp_property_application_update_section:
    path:     /{propertyId}/update-section/{sectionId}
    defaults: { _controller: ErpPropertyBundle:ApplicationForm:updateSection }
    methods: [POST]
    requirements:
        propertyId: \d+
        sectionId: \d+

erp_property_application_add_field:
    path:     /{propertyId}/section/{sectionId}/add-field
    defaults: { _controller: ErpPropertyBundle:ApplicationForm:addField }
    methods: [POST]
    requirements:
        propertyId: \d+
        sectionId: \d+

erp_property_application_remove_field:
    path:     /{propertyId}/remove-field/{fieldId}
    defaults: { _controller: ErpPropertyBundle:ApplicationForm:removeField }
    methods: [POST]
    requirements:
        propertyId: \d+
        fieldId: \d+

erp_property_application_form_save_application_fee:
    path:     /{property}/fee/save
    defaults: { _controller: ErpPropertyBundle:ApplicationForm:saveApplicationFee }
    methods: [POST]
    requirements:
        property: \d+

erp_property_application_form_copy_list:
    path:     /{propertyId}/copy-list
    defaults: { _controller: ErpPropertyBundle:ApplicationForm:copyList }
    methods: [GET]

erp_property_application_form_copy_complete:
    path:     /{propertyId}/copy-complete
    defaults: { _controller: ErpPropertyBundle:ApplicationForm:copyToOtherProperties }
    methods: [GET, POST]