<?php

namespace Erp\SiteBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * HomePageContentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HomePageContentRepository extends EntityRepository
{
    /**
     * Return last record
     *
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findLast()
    {
        $qb = $this->_em->createQueryBuilder()
            ->select('hpc')
            ->from($this->_entityName, 'hpc')
            ->orderBy('hpc.id', 'DESC')
        ;

        $result = $qb->getQuery()->getOneOrNullResult();

        return $result;
    }
}
