<?php

namespace Erp\WorkorderBundle\Entity;

/**
 * EditRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EditRepository extends \Doctrine\ORM\EntityRepository
{
    public function getNextId() {
        $qb = $this->_em->createQueryBuilder()
            ->select('a')
            ->from($this->_entityName, 'a')
            ->orderBy('a.id', 'DESC')
            ->setMaxResults(1);

        $result = $qb->getQuery()->getOneOrNullResult();

        return $result;
    }
}
