# This file is a "template" of what your parameters.yml file should look like
# Set parameters here that may be different on each deployment target of the app, e.g. development, staging, production.
# http://symfony.com/doc/current/best_practices/configuration.html#infrastructure-related-configuration
parameters:
    database_host:     127.0.0.1
    database_port:     ~
    database_name:     erentpay
    database_user:     root
    database_password: Ch4ng3me
    # You should uncomment this if you want use pdo_sqlite
    # database_path: "%kernel.root_dir%/data.db3"

    mailer_transport:  smtp
    mailer_host:       127.0.0.1
    mailer_user:       ~
    mailer_password:   ~

    # A secret key that's used to generate certain security-related tokens
    secret:            ThisTokenIsNotSoSecretChangeIt

    contact_email: info@erentpay.com
    siteUrl: 'https://erent-stage.oxagile.com'

    docusign_integrator_key: TEST-490cb1c8-1951-4cc0-be36-48edc610044b
    docusign_email: dmitry.budnitski@oxagile.com
    docusign_password: dmitry.budnitski@oxagile.com
    docusign_environment: demo
    docusign_account_id: a73c6d27-004a-4dea-8fe0-872354443292

    ga_id: 'UA-72964645-1'
