<?php

namespace Erp\PropertyBundle\Repository;

use Erp\PropertyBundle\Entity\ApplicationForm;
use Doctrine\ORM\EntityRepository;

/**
 * ApplicationSectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApplicationSectionRepository extends EntityRepository
{
    /**
     * Return sort number
     *
     * @param ApplicationForm $applicationForm
     *
     * @return int|mixed
     */
    public function getSortNumber(ApplicationForm $applicationForm)
    {
        $qb = $this->_em->createQueryBuilder()
            ->select('apps.sort')
            ->from($this->_entityName, 'apps')
            ->where('apps.applicationForm = :form')
            ->setParameter('form', $applicationForm)
            ->orderBy('apps.sort', 'DESC')
            ->setMaxResults(1)
        ;

        $result = $qb->getQuery()->getOneOrNullResult();
        $result = !$result ? 1 : $result['sort'] + 1;

        return $result;
    }
}
