<?php

namespace Erp\PropertyBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AppointmentRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppointmentRequestRepository extends EntityRepository
{
}
