<?php

namespace Erp\UserBundle\Repository;

/**
 * ForumCommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForumCommentRepository extends \Doctrine\ORM\EntityRepository
{
}
