<?php

namespace Erp\UserBundle\Repository;

use Erp\UserBundle\Entity\ForumTopic;

/**
 * ForumTopicRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ForumTopicRepository extends \Doctrine\ORM\EntityRepository
{
}
