<?php

namespace Erp\UserBundle\Repository;

use \Doctrine\ORM\EntityRepository;

/**
 * ProConsultantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProConsultantRepository extends EntityRepository
{
}
