<?php

namespace Erp\UserBundle\Repository;

use \Doctrine\ORM\EntityRepository;
use Erp\UserBundle\Entity\ProConsultant;
use Erp\UserBundle\Entity\ProReport;

/**
 * ProReportRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProReportRepository extends EntityRepository
{
    /**
     * @param \Erp\UserBundle\Entity\ProConsultant $proConsultant
     * @param                                      $month
     *
     * @return null|ProReport
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getByConsultantAndMonth(ProConsultant $proConsultant, $month)
    {
        $qb = $this->_em->createQueryBuilder()
            ->select('pr')
            ->from($this->_entityName, 'pr')
            ->where('pr.proConsultant = :proConsultant')
            ->andWhere('DATE_FORMAT(pr.approvedDate, \'%M\') = :month')
            ->setParameter('proConsultant', $proConsultant)
            ->setParameter('month', $month)
            ->setMaxResults(1);
        $result = $qb->getQuery()->getOneOrNullResult();

        return $result;
    }
}
