erp_user_user_allow_rent_payment:
     path:     /late-rent-payment/allow/{user}
     defaults: { _controller: ErpUserBundle:User:allowRentPayment }
     methods: [POST]
     requirements:
        userId: \d+