<?php

namespace Erp\CoreBundle\Repository;

/**
 * EmailNotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailNotificationRepository extends \Doctrine\ORM\EntityRepository
{
}
